WITH pay_register AS (
    SELECT * FROM {{ source('ukg', 'pay_register') }}
)

SELECT 
    CAST(id AS character varying) AS id,
    CAST(_fivetran_deleted AS boolean) AS _fivetran_deleted,
    CAST(company_id AS character varying) AS company_id,
    CAST(employee_id AS character varying) AS employee_id,
    CAST(employment_id AS character varying) AS employment_id,
    CAST(location_id AS character varying) AS location_id,
    CAST(organization_level_1_id AS character varying) AS organization_level_1_id,
    CAST(organization_level_2_id AS character varying) AS organization_level_2_id,
    CAST(organization_level_3_id AS character varying) AS organization_level_3_id,
    CAST(organization_level_4_id AS character varying) AS organization_level_4_id,
    CAST(pay_group AS character varying) AS pay_group,
    CAST(_fivetran_synced AS timestamp with time zone) AS _fivetran_synced,
    CAST(shift AS character varying) AS shift,
    CAST(project AS character varying) AS project,
    CAST(total_earnings_amount AS double precision) AS total_earnings_amount,
    CAST(ssn AS character varying) AS ssn,
    CAST(direct_deposit_amount AS double precision) AS direct_deposit_amount,
    CAST(job_code AS character varying) AS job_code,
    CAST(employee_status AS character varying) AS employee_status,
    CAST(bonus_total_ot_hours AS double precision) AS bonus_total_ot_hours,
    CAST(bonus_total_hours AS double precision) AS bonus_total_hours,
    CAST(document_number AS character varying) AS document_number,
    CAST(reconciled AS character varying) AS reconciled,
    CAST(is_voiding_record AS boolean) AS is_voiding_record,
    CAST(state_sui AS character varying) AS state_sui,
    CAST(hourly_pay_rate AS double precision) AS hourly_pay_rate,
    CAST(check_add_mode AS character varying) AS check_add_mode,
    CAST(total_shift_amount AS double precision) AS total_shift_amount,
    CAST(total_hours AS double precision) AS total_hours,
    CAST(name_middle AS character varying) AS name_middle,
    CAST(last_regular_pay_date AS timestamp without time zone) AS last_regular_pay_date,
    CAST(is_voided AS boolean) AS is_voided,
    CAST(is_regular_pay_for_cumulative AS character varying) AS is_regular_pay_for_cumulative,
    CAST(tax_calculation_group_id AS character varying) AS tax_calculation_group_id,
    CAST(check_amount AS double precision) AS check_amount,
    CAST(pay_period_frequency AS character varying) AS pay_period_frequency,
    CAST(total_hours_worked AS double precision) AS total_hours_worked,
    CAST(pay_date AS timestamp without time zone) AS pay_date,
    CAST(name_last AS character varying) AS name_last,
    CAST(currency_code AS character varying) AS currency_code,
    CAST(original_pay_period_frequency AS character varying) AS original_pay_period_frequency,
    CAST(earning_tax_reporting_type AS character varying) AS earning_tax_reporting_type,
    CAST(void_date AS timestamp without time zone) AS void_date,
    CAST(annual_salary AS double precision) AS annual_salary,
    CAST(total_tax_amount AS double precision) AS total_tax_amount,
    CAST(sui_gross AS double precision) AS sui_gross,
    CAST(name_first AS character varying) AS name_first,
    CAST(name_suffix AS character varying) AS name_suffix,
    CAST(reconcile_date AS timestamp without time zone) AS reconcile_date,
    CAST(tax_calculation_sequence AS character varying) AS tax_calculation_sequence,
    CAST(sequence_number AS integer) AS sequence_number,
    CAST(auto_allocate AS boolean) AS auto_allocate,
    CAST(total_deduction_amount AS double precision) AS total_deduction_amount,
    CAST(net_amount AS double precision) AS net_amount
FROM pay_register
