WITH compensation AS (
    SELECT * FROM {{ source('ukg', 'compensation') }}
)

SELECT 
    CAST(_fivetran_id AS character varying) AS _fivetran_id,
    CAST(date_in_job AS timestamp without time zone) AS date_in_job,
    CAST(_fivetran_deleted AS boolean) AS _fivetran_deleted,
    CAST(company_id AS character varying) AS company_id,
    CAST(employee_id AS character varying) AS employee_id,
    CAST(pay_group AS character varying) AS pay_group,
    CAST(primary_job_id AS character varying) AS primary_job_id,
    CAST(_fivetran_synced AS timestamp with time zone) AS _fivetran_synced,
    CAST(is_multiple_job AS boolean) AS is_multiple_job,
    CAST(date_last_worked AS timestamp without time zone) AS date_last_worked,
    CAST(job_title AS character varying) AS job_title,
    CAST(piece_pay_rate AS double precision) AS piece_pay_rate,
    CAST(weekly_pay_rate AS double precision) AS weekly_pay_rate,
    CAST(total_ann_salary AS double precision) AS total_ann_salary,
    CAST(hourly_pay_rate AS double precision) AS hourly_pay_rate,
    CAST(primary_shift_group_code AS character varying) AS primary_shift_group_code,
    CAST(bonus_total_ot_hrs AS double precision) AS bonus_total_ot_hrs,
    CAST(scheduled_period_work_hours AS double precision) AS scheduled_period_work_hours,
    CAST(job_change_reason_code AS character varying) AS job_change_reason_code,
    CAST(is_seasonal_worker AS boolean) AS is_seasonal_worker,
    CAST(distribution_center_code AS character varying) AS distribution_center_code,
    CAST(scheduled_full_time_equivalency AS double precision) AS scheduled_full_time_equivalency,
    CAST(salary_or_hourly_code AS character varying) AS salary_or_hourly_code,
    CAST(empl_status AS character varying) AS empl_status,
    CAST(date_last_paid AS timestamp without time zone) AS date_last_paid,
    CAST(primary_shift_code AS character varying) AS primary_shift_code,
    CAST(bonus_total_hrs AS double precision) AS bonus_total_hrs,
    CAST(pay_group_description AS character varying) AS pay_group_description,
    CAST(annual_salary AS double precision) AS annual_salary,
    CAST(is_auto_paid AS boolean) AS is_auto_paid,
    CAST(date_of_next_salayr_review AS timestamp without time zone) AS date_of_next_salayr_review,
    CAST(is_auto_allocated AS boolean) AS is_auto_allocated,
    CAST(is_highly_compensated AS boolean) AS is_highly_compensated,
    CAST(pay_period_pay_rate AS double precision) AS pay_period_pay_rate,
    CAST(job_salary_grade AS character varying) AS job_salary_grade,
    CAST(other_rate_1 AS double precision) AS other_rate_1,
    CAST(pay_period AS character varying) AS pay_period,
    CAST(full_time_or_part_time_code AS character varying) AS full_time_or_part_time_code,
    CAST(other_rate_3 AS double precision) AS other_rate_3,
    CAST(other_rate_2 AS double precision) AS other_rate_2,
    CAST(weekly_hours AS double precision) AS weekly_hours,
    CAST(other_rate_4 AS double precision) AS other_rate_4,
    CAST(scheduled_annual_work_hours AS double precision) AS scheduled_annual_work_hours,
    CAST(date_paid_thru AS timestamp without time zone) AS date_paid_thru,
    CAST(number_of_payments AS integer) AS number_of_payments,
    CAST(avg_pay_rate_cur_per AS double precision) AS avg_pay_rate_cur_per,
    CAST(performance_review_type AS character varying) AS performance_review_type,
    CAST(performance_review_rating AS character varying) AS performance_review_rating
FROM compensation