WITH ad_group_criterion_history AS (
    SELECT * FROM {{ source('google_ads', 'ad_group_criterion_history') }}
)

SELECT 
    CAST(ad_group_id AS bigint) AS ad_group_id,
    CAST(id AS bigint) AS id,
    CAST(updated_at AS timestamp with time zone) AS updated_at,
    CAST(user_interest_id AS bigint) AS user_interest_id,
    CAST(user_list_id AS bigint) AS user_list_id,
    CAST(age_range_type AS character varying) AS age_range_type,
    CAST(app_payment_model_type AS character varying) AS app_payment_model_type,
    CAST(approval_status AS character varying) AS approval_status,
    CAST(bid_modifier AS double precision) AS bid_modifier,
    CAST(cpc_bid_micros AS bigint) AS cpc_bid_micros,
    CAST(cpm_bid_micros AS bigint) AS cpm_bid_micros,
    CAST(cpv_bid_micros AS bigint) AS cpv_bid_micros,
    CAST(custom_affinity_id AS bigint) AS custom_affinity_id,
    CAST(custom_audience_id AS bigint) AS custom_audience_id,
    CAST(custom_intent_id AS bigint) AS custom_intent_id,
    CAST(disapproval_reasons AS character varying) AS disapproval_reasons,
    CAST(display_name AS character varying) AS display_name,
    CAST(final_mobile_urls AS character varying) AS final_mobile_urls,
    CAST(final_urls AS character varying) AS final_urls,
    CAST(final_url_suffix AS character varying) AS final_url_suffix,
    CAST(first_page_cpc_micros AS bigint) AS first_page_cpc_micros,
    CAST(first_position_cpc_micros AS bigint) AS first_position_cpc_micros,
    CAST(gender_type AS character varying) AS gender_type,
    CAST(income_range_type AS character varying) AS income_range_type,
    CAST(keyword_match_type AS character varying) AS keyword_match_type,
    CAST(keyword_text AS character varying) AS keyword_text,
    CAST(mobile_app_category_constant_id AS integer) AS mobile_app_category_constant_id,
    CAST(mobile_app_category_constant_name AS character varying) AS mobile_app_category_constant_name,
    CAST(mobile_application_app_id AS character varying) AS mobile_application_app_id,
    CAST(mobile_application_name AS character varying) AS mobile_application_name,
    CAST(negative AS boolean) AS negative,
    CAST(parent_ad_group_criterion_id AS bigint) AS parent_ad_group_criterion_id,
    CAST(parental_status_type AS character varying) AS parental_status_type,
    CAST(placement_url AS character varying) AS placement_url,
    CAST(quality_info_score AS integer) AS quality_info_score,
    CAST(quality_info_creative_score AS character varying) AS quality_info_creative_score,
    CAST(quality_info_post_click_score AS character varying) AS quality_info_post_click_score,
    CAST(quality_info_search_predicted_ctr AS character varying) AS quality_info_search_predicted_ctr,
    CAST(status AS character varying) AS status,
    CAST(system_serving_status AS character varying) AS system_serving_status,
    CAST(top_of_page_cpc_micros AS bigint) AS top_of_page_cpc_micros,
    CAST(topic_constant_id AS bigint) AS topic_constant_id,
    CAST(tracking_url_template AS character varying) AS tracking_url_template,
    CAST(type AS character varying) AS type,
    CAST(webpage_conditions AS character varying) AS webpage_conditions,
    CAST(youtube_channel_id AS character varying) AS youtube_channel_id,
    CAST(youtube_video_id AS character varying) AS youtube_video_id,
    CAST(_fivetran_synced AS timestamp with time zone) AS _fivetran_synced,
    CAST(_fivetran_start AS timestamp with time zone) AS _fivetran_start,
    CAST(_fivetran_end AS timestamp with time zone) AS _fivetran_end,
    CAST(_fivetran_active AS boolean) AS _fivetran_active
FROM ad_group_criterion_history