WITH gl_detail AS (
    SELECT * FROM {{ source('sage', 'gl_detail') }}
)

SELECT
    CAST(recordno AS character varying) AS recordno,
    CAST(_fivetran_deleted AS boolean) AS _fivetran_deleted,
    CAST(_fivetran_synced AS timestamp with time zone) AS _fivetran_synced,
    CAST(tr_type AS bigint) AS tr_type,
    CAST(accounttitle AS character varying) AS accounttitle,
    CAST(adj AS boolean) AS adj,
    CAST(vendorname AS character varying) AS vendorname,
    CAST(basecurr AS character varying) AS basecurr,
    CAST(amount AS double precision) AS amount,
    CAST(prcleared AS character varying) AS prcleared,
    CAST(batch_date AS date) AS batch_date,
    CAST(glentrykey AS bigint) AS glentrykey,
    CAST(batch_state AS character varying) AS batch_state,
    CAST(document AS character varying) AS document,
    CAST(debitamount AS double precision) AS debitamount,
    CAST(clrdate AS date) AS clrdate,
    CAST(modifiedby AS bigint) AS modifiedby,
    CAST(batch_no AS bigint) AS batch_no,
    CAST(totalentered AS double precision) AS totalentered,
    CAST(recordid AS character varying) AS recordid,
    CAST(symbol AS character varying) AS symbol,
    CAST(trx_amount AS double precision) AS trx_amount,
    CAST(docnumber AS character varying) AS docnumber,
    CAST(ownershipkey AS bigint) AS ownershipkey,
    CAST(line_no AS bigint) AS line_no,
    CAST(modified AS timestamp with time zone) AS modified,
    CAST(entry_state AS character varying) AS entry_state,
    CAST(accountno AS bigint) AS accountno,
    CAST(locationid AS character varying) AS locationid,
    CAST(trx_debitamount AS double precision) AS trx_debitamount,
    CAST(departmentid AS character varying) AS departmentid,
    CAST(modulekey AS character varying) AS modulekey,
    CAST(whencreated AS date) AS whencreated,
    CAST(state AS character varying) AS state,
    CAST(totalpaid AS double precision) AS totalpaid,
    CAST(batch_title AS character varying) AS batch_title,
    CAST(recordtype AS character varying) AS recordtype,
    CAST(totaldue AS double precision) AS totaldue,
    CAST(classdimkey AS bigint) AS classdimkey,
    CAST(whenmodified AS timestamp with time zone) AS whenmodified,
    CAST(cleared AS character varying) AS cleared,
    CAST(whendue AS date) AS whendue,
    CAST(auwhencreated AS timestamp with time zone) AS auwhencreated,
    CAST(vendordimkey AS bigint) AS vendordimkey,
    CAST(vendorid AS character varying) AS vendorid,
    CAST(description AS character varying) AS description,
    CAST(statistical AS boolean) AS statistical,
    CAST(creditamount AS double precision) AS creditamount,
    CAST(bookid AS character varying) AS bookid,
    CAST(departmenttitle AS character varying) AS departmenttitle,
    CAST(vendentity AS character varying) AS vendentity,
    CAST(createdby AS character varying) AS createdby,
    CAST(aucreatedby AS bigint) AS aucreatedby,
    CAST(trx_creditamount AS double precision) AS trx_creditamount,
    CAST(classid AS bigint) AS classid,
    CAST(currency AS character varying) AS currency,
    CAST(financialentity AS character varying) AS financialentity,
    CAST(classname AS character varying) AS classname,
    CAST(prclrdate AS date) AS prclrdate,
    CAST(referenceno AS character varying) AS referenceno,
    CAST(locationname AS character varying) AS locationname,
    CAST(whenpaid AS date) AS whenpaid,
    "prdescription-deprecated-92ce0e4d-739f-4891-b017-e295b5d86994",
    CAST(entry_date AS date) AS entry_date,
    CAST(entrydescription AS character varying) AS entrydescription,
    CAST(batchkey AS character varying) AS batchkey,
    "prdescription-deprecated-eebc62c5-5825-4bbf-bd84-f6247f0b3efb",
    CAST(prdescription AS character varying) AS prdescription
FROM gl_detail