WITH ap_bill_item AS (
    SELECT * FROM  {{ source ('sage_ap', 'ap_bill') }}
)
 
SELECT
    recordkey AS record_key,
    recordno AS record_num,
    _fivetran_synced,
    accountkey AS account_key,
    accounttitle AS account_title,
    amount AS amount,
    
    retainagepercentage AS retainage_percentage,
    billed,
    recordid AS record_id,
    amountretained AS amount_retained,
    locationid,
    totalpaid,
    whenmodified,
    vendordimkey,
    billable,
    is_cip,
    includetaxinassetcost,
    classname,
    locationname,
    trx_totalselected,
    entrydescription,
    offsetglaccounttitle,
    vendorname,
    lineitem,
    basecurr,
    baselocation,
    paymenttaxcapture,
    form_1099_box,
    form_1099,
    modifiedby,
    exchange_rate,
    partialexempt,
    record_url,
    departmentname,
    trx_amount,
    line_no,
    accountno,
    totalselected,
    departmentid,
    whencreated,
    state,
    is_asset,
    recordtype,
    prentryoffsetaccountno,
    classdimkey,
    vendorid,
    createdby,
    classid,
    currency,
    form_1099_type,
    offsetglaccountno,
    offsetaccountkey,
    trx_totalpaid,
    entry_date
FROM ap_bill_item
