WITH ap_bill_item AS (
    SELECT * FROM  {{ source ('sage_ap', 'ap_bill_item') }}
)
 
SELECT
    recordkey AS record_num, 
    recordno AS record_line_item_num,
    recordid AS invoice_num, 
    state AS line_item_state,
    vendorid AS vendor_id,
    vendordimkey AS vendor_dim_key,
    vendorname AS vendor_name,
    line_no,
    accountno AS account_no,
    accountkey AS account_sage_id,
    accounttitle AS account_title,
    departmentname AS department_name,
    departmentid AS department_id,
    amount,
    classname AS class_name,
    classdimkey AS class_dim_key,
    classid AS class_id,
    amountretained AS amount_retained,
    totalpaid AS total_paid,
    whencreated AS when_created,
    whenmodified AS when_modified,
    entry_date, 
    locationid AS location_id,
    locationname AS location_name,
    entrydescription AS entry_description,
    billable,
    billed,
    is_cip,
    modifiedby AS modified_by,
    includetaxinassetcost AS include_tax_in_asset_cost,
    offsetglaccounttitle AS offset_gl_account_title,
    lineitem AS line_item,
    basecurr AS base_curr,
    baselocation AS base_location,
    paymenttaxcapture AS payment_tax_capture,
    exchange_rate,
    partialexempt AS partial_exempt,
    totalselected AS total_selected,
    is_asset,
    retainagepercentage AS retainage_percentage,
    trx_totalpaid AS trx_total_paid,
    trx_totalselected AS trx_total_selected,
    trx_amount,
    recordtype AS record_type,
    prentryoffsetaccountno AS pr_entry_offset_account_no,
    createdby AS created_by,
    currency,
    record_url,
    form_1099_type,
    form_1099_box,
    form_1099,
    offsetglaccountno AS offset_gl_account_no,
    offsetaccountkey AS offset_account_key,
    _fivetran_synced
FROM ap_bill_item
